### ISSUE TITLE
RNA string needs to be reversed!

### ISSUE THREAD

**Issue by ali-ramadhan** [project-lovelace/lovelace-problems#36]
https://www.reddit.com/r/learnprogramming/comments/cgr7eg/ten_easy_scientific_programming_problems/euljuoc/

**Comment by benallan** [comment]
When I've seen the same problem RNA transcription problem elsewhere, it was usually described as a translation "map", like the following:

```
def rna(dna):
    # G -> C
    # C -> G
    # T -> A
    # A -> U
    trans = str.maketrans("GCTA", "CGAU")
    return dna.translate(trans)
```

I've no idea how biologically accurate and easy to understand that method is though!

**Comment by ali-ramadhan** [comment]
Ah I had to Google but I think that's the DNA complement rather than the RNA?

I think the Reddit post was talking about also reversing the string to be biologically accurate. You can tell I'm no biologist lol.

Would just have to change the solution and update the website description (nothing major), maybe the problem module but don't think so.

**Comment by benallan** [comment]
Yeah I'm most definitely no biologist either so won't pretend I know which is correct. It's quite possible that the other problems I've seen are also written by non-biologists (and shouldn't be lazily copied), but for reference here's the example I mentioned above:
https://github.com/exercism/javascript/tree/master/exercises/rna-transcription

**Comment by ali-ramadhan** [comment]
Solution and website description have been fixed.
