### ISSUE TITLE
Bug in verifying flight paths solution

### ISSUE THREAD

**Issue by ali-ramadhan** [project-lovelace/lovelace-problems#37]
Reported here: https://www.reddit.com/r/Physics/comments/cgr9s3/project_lovelace_learn_physics_and_programming/eum125p/

Somehow this solution passes all the test cases lol and I have no idea why:
```python
from math import radians, sqrt, asin, sin, cos

def haversine_distance(lat1, lon1, lat2, lon2):
    return asin
```

**Comment by benallan** [comment]
Hi, I've been using the project lovelace website a bit and stumbled across this bug report. I hope you don't mind I had a quick look and think I can explain why this issue happens. 

So firstly, in `problems.test_case.test_case_solution_correct()` you loop over each output variable and check if it's correct or not:

```
    # Assume user output is correct until we find a mismatching value.
    test_case_passed = True

    # Verify that every output matches.
    for i, var in enumerate(output_vars):
        var_type = type(user_test_case.output[var])
        user_val = user_test_case.output[var]
```

This is a bit risky: it assumes correctness to begin with, and the for loop will effectively be skipped if the `output_vars` dict is empty. You could either check output_vars before the loop, or use a for-else construct to stop cases like this sneaking through.

Why is output vars empty? Well it seems that the init of `problems.test_case.TestCase` zips the output_vars together with the output tuple:
```
            for var, val in zip(output_vars, output_tuple):
```
But if this output tuple is empty, then this for loop will effectively be skipped like before. `zip_longest` might help, or I guess that in your case you always expect the length of output_vars to match output_tuple? So you could maybe check that the lengths match explicitly.

I'm still not sure how the user's output ended up as an empty tuple though!

**Comment by ali-ramadhan** [comment]
Hey @benallan, thanks for looking into this! I'm somewhat amazed you were able to navigate our somewhat messy code lol.

> This is a bit risky: it assumes correctness to begin with, and the for loop will effectively be skipped if the output_vars dict is empty. You could either check output_vars before the loop, or use a for-else construct to stop cases like this sneaking through.

Ah that's a good point.  I'll try switching it to start with `False` then only set `passed = True` if all test cases pass. Didn't even know about `for else` statements!

> But if this output tuple is empty, then this for loop will effectively be skipped too. `zip_longest` might help, or I guess that in your case you always expect the length of output_vars to match output_tuple? So you could maybe check that the lengths match explicitly.

Nice catch! Yeah that loop is probably being skipped. I think I'll change it return `passed = False` is the two tuples are of different sizes because that's a wrong answer, which should solve this.

> I'm still not sure how the user's output ended up as an empty tuple though!

Still a mystery to me as well!

**Comment by benallan** [comment]
Glad it helped!
