### ISSUE TITLE
Game of Life: Oscillator test case expected result is wrong.

### ISSUE THREAD

**Issue by TheConanRider** [project-lovelace/lovelace-problems#41]
The expected result from the oscillator test case seems to be checking against a random solution.

https://imgur.com/a/mJECYd7

On the left is the result you should expect i.e the second stage of each oscillator and on the right is the result the test case checks against.

**Comment by ali-ramadhan** [comment]
Hey @TheConanRider thanks for reporting this! Definitely something fishy happening under the hood. Looking into it right now...

PS: Nice spreadsheet plots!

**Comment by ali-ramadhan** [comment]
@TheConanRider should be fixed now by commit c40e48250bb233bffb59eed6f94aecd26c483340!

Let me know if it works for you now.

**Comment by TheConanRider** [comment]
Issue seems to be resolved. 
https://imgur.com/a/1ky8i3q

(Left: Expected result, Middle: Previous Solution, Right: Current Solution)

This also fixed a related issue with the third test case "glider gun".

Closed as Fixed.

**Comment by ali-ramadhan** [comment]
Awesome! Thanks for the report, and sorry for any frustration it caused.
