### ISSUE TITLE
Record version of problems repo

### ISSUE THREAD

**Issue by benallan** [project-lovelace/lovelace-problems#46]
Just an idea, but it might be helpful to give the overall problems repo a version number, then bump the version either when the problems have been tested and are good to go, or when they're pushed to the website. 

I'm thinking this might help coordinate all the different repos: when I'm working on the engine, sometimes tests are failing because the problems (or solutions) are under development. This is a bit confusing, so perhaps the engine tests could run against a fixed version of the problems, e.g. 0.1.0. Then development of the problems could continue without affecting the engine. But we could optionally run the engine tests against the latest version of problems too if that's useful.

**Comment by ali-ramadhan** [comment]
That's a good idea. Right now I guess we synchronize releases among all three repositories, which is kind of arbitrary but for this repo it might make the most sense to just tag a new release every time a new problem is added.

**Comment by ali-ramadhan** [comment]
@benallan I'm tagging releases more frequently now plus lovelace-problems and lovelace-solutions now have their own test suites so hopefully we won't have as many frustrating failures.
