### ISSUE TITLE
"Exponential growth" Javascript submission does not work

### ISSUE THREAD

**Issue by tiitlan** [project-lovelace/lovelace-problems#76]
The progress bar just keeps on circling.

**Comment by paniash** [comment]
@tiitlan Hi! This happens if the server is busy. We're currently using only one gunicorn engine server. Bumping it up a bit will help for sure. See [this](https://github.com/project-lovelace/lovelace-website/pull/148).

**Comment by tiitlan** [comment]
Thanks for clarifying.
